### ISSUE TITLE
Add example TA1 and TA3 reports to repo for local development

### ISSUE THREAD

**Issue by Sorrento110** [DARPA-ASKEM/integration-dashboard#10]
An example report of TA1 test suite and TA3 test suite should be added to the repository for local development and verbose documentation of the process.

Could be added to some `example_reports/` with a `TA1.json` and `TA3.json`.

**Comment by fivegrant** [comment]
solved: https://github.com/DARPA-ASKEM/integration-dashboard/commit/52e1732d5a0dd5f630e2440eb4ec87a7005ede00
